# Generated by Django 5.2.7 on 2025-10-12 23:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='information',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
